#' Convert a set of eastings/northings to grid references
#'
#' @description
#' Takes a dataframe of British National grid eastings and northings and converts to standard grid
#' reference of desired resolution. Note this only works for locations in Great Britain.
#'
#' @param df name of input dataframe
#' @param res resolution of desired grid reference (100, 50, 20, 10, 2, 1km)
#' @param outname optional desired name of output grid reference variable (e.g. 'tenkm')
#'
#' @return The same dataframe with additional column for the requested grid reference, either
#' named 'gref' or optionally renamed
#'
#' @examples
#' temp<-data.frame(cbc_code='R.',count=10,easting=552713.37,northing=292678.498)
#' temp2<-coords_to_gridref(temp,2,'tetrad_id')
#' print(temp2)
#' cbc_code count  easting northing tetrad_id
#'       R.    10 552713.4 292678.5     TL59G
#'
#' @export
#'
coords_to_gridref<-function(df,res,outname='gref') {
  #only run if res is an expected grid resolution
  if(res %in% c(1,2,10,20,50,100)) {
    #list of names in starting df (needed to ensure correct export at end)
    dfnams<-names(df)

    #split easting and northing into components
    df$e100<-floor( df$easting/100000)
    df$e10 <-floor( (df$easting-(df$e100*100000) ) /10000)
    df$e1  <-floor( (df$easting-((df$e100*100000)+(df$e10*10000) ))  /1000)
    df$e01 <-floor( (df$easting-((df$e100*100000)+(df$e10*10000)+(df$e1*1000) )) /100)
    df$n100<-floor( df$northing/100000)
    df$n10 <-floor((df$northing-(df$n100*100000) ) /10000)
    df$n1  <-floor((df$northing-((df$n100*100000)+(df$n10*10000) )) /1000)
    df$n01 <-floor((df$northing-((df$n100*100000)+(df$n10*10000)+(df$n1*1000) )) /100)

    #calculate 100-km letters and 10-km reference which are needed in several resolutions.
    #NB give Northern Irish squares off the BNG a dummy XX
    df$hundref<-NA
    df$hundref<-ifelse(df$e100==0 & df$n100==0,'SV',df$hundref)
    df$hundref<-ifelse(df$e100==1 & df$n100==0,'SW',df$hundref)
    df$hundref<-ifelse(df$e100==2 & df$n100==0,'SX',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==0,'SY',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==0,'SZ',df$hundref)
    df$hundref<-ifelse(df$e100==5 & df$n100==0,'TV',df$hundref)
    df$hundref<-ifelse(df$e100==1 & df$n100==1,'SR',df$hundref)
    df$hundref<-ifelse(df$e100==2 & df$n100==1,'SS',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==1,'ST',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==1,'SU',df$hundref)
    df$hundref<-ifelse(df$e100==5 & df$n100==1,'TQ',df$hundref)
    df$hundref<-ifelse(df$e100==6 & df$n100==1,'TR',df$hundref)
    df$hundref<-ifelse(df$e100==1 & df$n100==2,'SM',df$hundref)
    df$hundref<-ifelse(df$e100==2 & df$n100==2,'SN',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==2,'SO',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==2,'SP',df$hundref)
    df$hundref<-ifelse(df$e100==5 & df$n100==2,'TL',df$hundref)
    df$hundref<-ifelse(df$e100==6 & df$n100==2,'TM',df$hundref)
    df$hundref<-ifelse(df$e100==2 & df$n100==3,'SH',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==3,'SJ',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==3,'SK',df$hundref)
    df$hundref<-ifelse(df$e100==5 & df$n100==3,'TF',df$hundref)
    df$hundref<-ifelse(df$e100==6 & df$n100==3,'TG',df$hundref)
    df$hundref<-ifelse(df$e100==0 & df$n100==4,'XX',df$hundref)
    df$hundref<-ifelse(df$e100==1 & df$n100==4,'XX',df$hundref)
    df$hundref<-ifelse(df$e100==2 & df$n100==4,'SC',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==4,'SD',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==4,'SE',df$hundref)
    df$hundref<-ifelse(df$e100==5 & df$n100==4,'TA',df$hundref)
    df$hundref<-ifelse(df$e100==0 & df$n100==5,'XX',df$hundref)
    df$hundref<-ifelse(df$e100==1 & df$n100==5,'NW',df$hundref)
    df$hundref<-ifelse(df$e100==2 & df$n100==5,'NX',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==5,'NY',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==5,'NZ',df$hundref)
    df$hundref<-ifelse(df$e100==1 & df$n100==6,'NR',df$hundref)
    df$hundref<-ifelse(df$e100==2 & df$n100==6,'NS',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==6,'NT',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==6,'NU',df$hundref)
    df$hundref<-ifelse(df$e100==0 & df$n100==7,'NL',df$hundref)
    df$hundref<-ifelse(df$e100==1 & df$n100==7,'NM',df$hundref)
    df$hundref<-ifelse(df$e100==2 & df$n100==7,'NN',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==7,'NO',df$hundref)
    df$hundref<-ifelse(df$e100==0 & df$n100==8,'NF',df$hundref)
    df$hundref<-ifelse(df$e100==1 & df$n100==8,'NG',df$hundref)
    df$hundref<-ifelse(df$e100==2 & df$n100==8,'NH',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==8,'NJ',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==8,'NK',df$hundref)
    df$hundref<-ifelse(df$e100==0 & df$n100==9,'NA',df$hundref)
    df$hundref<-ifelse(df$e100==1 & df$n100==9,'NB',df$hundref)
    df$hundref<-ifelse(df$e100==2 & df$n100==9,'NC',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==9,'ND',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==10,'HY',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==10,'HZ',df$hundref)
    df$hundref<-ifelse(df$e100==3 & df$n100==11,'HT',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==11,'HU',df$hundref)
    df$hundref<-ifelse(df$e100==4 & df$n100==12,'HP',df$hundref)

    df$tenkm<-paste0(df$hundref,df$e10,df$n10)

    #code up 100-km
    if(res==100) {
      df$gref<-df$hundref
    }

    #code up 50-km
    if(res==50) {
      df$quadref<-NA
      df$quadref<-ifelse(df$e10<=4 & df$n10<=4, 'SW',df$quadref)
      df$quadref<-ifelse(df$e10<=4 & df$n10>4, 'NW',df$quadref)
      df$quadref<-ifelse(df$e10>4 & df$n10>4, 'NE',df$quadref)
      df$quadref<-ifelse(df$e10>4 & df$n10<=4, 'SE',df$quadref)
      df$gref<-paste0(df$hundref,df$quadref)
    }

    #code up 20-km
    if(res==20) {
      df$segref<-NA
      df$segref<-ifelse(df$e10==0 & df$n10==0,'_A',df$segref)
      df$segref<-ifelse(df$e10==0 & df$n10==1,'_A',df$segref)
      df$segref<-ifelse(df$e10==1 & df$n10==0,'_A',df$segref)
      df$segref<-ifelse(df$e10==1 & df$n10==1,'_A',df$segref)
      df$segref<-ifelse(df$e10==2 & df$n10==0,'_F',df$segref)
      df$segref<-ifelse(df$e10==2 & df$n10==1,'_F',df$segref)
      df$segref<-ifelse(df$e10==3 & df$n10==0,'_F',df$segref)
      df$segref<-ifelse(df$e10==3 & df$n10==1,'_F',df$segref)
      df$segref<-ifelse(df$e10==4 & df$n10==0,'_K',df$segref)
      df$segref<-ifelse(df$e10==4 & df$n10==1,'_K',df$segref)
      df$segref<-ifelse(df$e10==5 & df$n10==0,'_K',df$segref)
      df$segref<-ifelse(df$e10==5 & df$n10==1,'_K',df$segref)
      df$segref<-ifelse(df$e10==6 & df$n10==0,'_Q',df$segref)
      df$segref<-ifelse(df$e10==6 & df$n10==1,'_Q',df$segref)
      df$segref<-ifelse(df$e10==7 & df$n10==0,'_Q',df$segref)
      df$segref<-ifelse(df$e10==7 & df$n10==1,'_Q',df$segref)
      df$segref<-ifelse(df$e10==8 & df$n10==0,'_V',df$segref)
      df$segref<-ifelse(df$e10==8 & df$n10==1,'_V',df$segref)
      df$segref<-ifelse(df$e10==9 & df$n10==0,'_V',df$segref)
      df$segref<-ifelse(df$e10==9 & df$n10==1,'_V',df$segref)
      df$segref<-ifelse(df$e10==0 & df$n10==2,'_B',df$segref)
      df$segref<-ifelse(df$e10==0 & df$n10==3,'_B',df$segref)
      df$segref<-ifelse(df$e10==1 & df$n10==2,'_B',df$segref)
      df$segref<-ifelse(df$e10==1 & df$n10==3,'_B',df$segref)
      df$segref<-ifelse(df$e10==2 & df$n10==2,'_G',df$segref)
      df$segref<-ifelse(df$e10==2 & df$n10==3,'_G',df$segref)
      df$segref<-ifelse(df$e10==3 & df$n10==2,'_G',df$segref)
      df$segref<-ifelse(df$e10==3 & df$n10==3,'_G',df$segref)
      df$segref<-ifelse(df$e10==4 & df$n10==2,'_L',df$segref)
      df$segref<-ifelse(df$e10==4 & df$n10==3,'_L',df$segref)
      df$segref<-ifelse(df$e10==5 & df$n10==2,'_L',df$segref)
      df$segref<-ifelse(df$e10==5 & df$n10==3,'_L',df$segref)
      df$segref<-ifelse(df$e10==6 & df$n10==2,'_R',df$segref)
      df$segref<-ifelse(df$e10==6 & df$n10==3,'_R',df$segref)
      df$segref<-ifelse(df$e10==7 & df$n10==2,'_R',df$segref)
      df$segref<-ifelse(df$e10==7 & df$n10==3,'_R',df$segref)
      df$segref<-ifelse(df$e10==8 & df$n10==2,'_W',df$segref)
      df$segref<-ifelse(df$e10==8 & df$n10==3,'_W',df$segref)
      df$segref<-ifelse(df$e10==9 & df$n10==2,'_W',df$segref)
      df$segref<-ifelse(df$e10==9 & df$n10==3,'_W',df$segref)
      df$segref<-ifelse(df$e10==0 & df$n10==4,'_C',df$segref)
      df$segref<-ifelse(df$e10==0 & df$n10==5,'_C',df$segref)
      df$segref<-ifelse(df$e10==1 & df$n10==4,'_C',df$segref)
      df$segref<-ifelse(df$e10==1 & df$n10==5,'_C',df$segref)
      df$segref<-ifelse(df$e10==2 & df$n10==4,'_H',df$segref)
      df$segref<-ifelse(df$e10==2 & df$n10==5,'_H',df$segref)
      df$segref<-ifelse(df$e10==3 & df$n10==4,'_H',df$segref)
      df$segref<-ifelse(df$e10==3 & df$n10==5,'_H',df$segref)
      df$segref<-ifelse(df$e10==4 & df$n10==4,'_M',df$segref)
      df$segref<-ifelse(df$e10==4 & df$n10==5,'_M',df$segref)
      df$segref<-ifelse(df$e10==5 & df$n10==4,'_M',df$segref)
      df$segref<-ifelse(df$e10==5 & df$n10==5,'_M',df$segref)
      df$segref<-ifelse(df$e10==6 & df$n10==4,'_S',df$segref)
      df$segref<-ifelse(df$e10==6 & df$n10==5,'_S',df$segref)
      df$segref<-ifelse(df$e10==7 & df$n10==4,'_S',df$segref)
      df$segref<-ifelse(df$e10==7 & df$n10==5,'_S',df$segref)
      df$segref<-ifelse(df$e10==8 & df$n10==4,'_X',df$segref)
      df$segref<-ifelse(df$e10==8 & df$n10==5,'_X',df$segref)
      df$segref<-ifelse(df$e10==9 & df$n10==4,'_X',df$segref)
      df$segref<-ifelse(df$e10==9 & df$n10==5,'_X',df$segref)
      df$segref<-ifelse(df$e10==0 & df$n10==6,'_D',df$segref)
      df$segref<-ifelse(df$e10==0 & df$n10==7,'_D',df$segref)
      df$segref<-ifelse(df$e10==1 & df$n10==6,'_D',df$segref)
      df$segref<-ifelse(df$e10==1 & df$n10==7,'_D',df$segref)
      df$segref<-ifelse(df$e10==2 & df$n10==6,'_I',df$segref)
      df$segref<-ifelse(df$e10==2 & df$n10==7,'_I',df$segref)
      df$segref<-ifelse(df$e10==3 & df$n10==6,'_I',df$segref)
      df$segref<-ifelse(df$e10==3 & df$n10==7,'_I',df$segref)
      df$segref<-ifelse(df$e10==4 & df$n10==6,'_N',df$segref)
      df$segref<-ifelse(df$e10==4 & df$n10==7,'_N',df$segref)
      df$segref<-ifelse(df$e10==5 & df$n10==6,'_N',df$segref)
      df$segref<-ifelse(df$e10==5 & df$n10==7,'_N',df$segref)
      df$segref<-ifelse(df$e10==6 & df$n10==6,'_T',df$segref)
      df$segref<-ifelse(df$e10==6 & df$n10==7,'_T',df$segref)
      df$segref<-ifelse(df$e10==7 & df$n10==6,'_T',df$segref)
      df$segref<-ifelse(df$e10==7 & df$n10==7,'_T',df$segref)
      df$segref<-ifelse(df$e10==8 & df$n10==6,'_Y',df$segref)
      df$segref<-ifelse(df$e10==8 & df$n10==7,'_Y',df$segref)
      df$segref<-ifelse(df$e10==9 & df$n10==6,'_Y',df$segref)
      df$segref<-ifelse(df$e10==9 & df$n10==7,'_Y',df$segref)
      df$segref<-ifelse(df$e10==0 & df$n10==8,'_E',df$segref)
      df$segref<-ifelse(df$e10==0 & df$n10==9,'_E',df$segref)
      df$segref<-ifelse(df$e10==1 & df$n10==8,'_E',df$segref)
      df$segref<-ifelse(df$e10==1 & df$n10==9,'_E',df$segref)
      df$segref<-ifelse(df$e10==2 & df$n10==8,'_J',df$segref)
      df$segref<-ifelse(df$e10==2 & df$n10==9,'_J',df$segref)
      df$segref<-ifelse(df$e10==3 & df$n10==8,'_J',df$segref)
      df$segref<-ifelse(df$e10==3 & df$n10==9,'_J',df$segref)
      df$segref<-ifelse(df$e10==4 & df$n10==8,'_P',df$segref)
      df$segref<-ifelse(df$e10==4 & df$n10==9,'_P',df$segref)
      df$segref<-ifelse(df$e10==5 & df$n10==8,'_P',df$segref)
      df$segref<-ifelse(df$e10==5 & df$n10==9,'_P',df$segref)
      df$segref<-ifelse(df$e10==6 & df$n10==8,'_U',df$segref)
      df$segref<-ifelse(df$e10==6 & df$n10==9,'_U',df$segref)
      df$segref<-ifelse(df$e10==7 & df$n10==8,'_U',df$segref)
      df$segref<-ifelse(df$e10==7 & df$n10==9,'_U',df$segref)
      df$segref<-ifelse(df$e10==8 & df$n10==8,'_Z',df$segref)
      df$segref<-ifelse(df$e10==8 & df$n10==9,'_Z',df$segref)
      df$segref<-ifelse(df$e10==9 & df$n10==8,'_Z',df$segref)
      df$segref<-ifelse(df$e10==9 & df$n10==9,'_Z',df$segref)
      df$gref<-paste0(df$hundref,df$segref)
    }

    #code up 10-km
    if(res==10) {
      df$gref<-df$tenkm
    }

    #code up tetrad
    if(res==2) {
      df$tetlet<-NA
      df$tetlet<-ifelse(df$e1==0 & df$n1==0,'A',df$tetlet)
      df$tetlet<-ifelse(df$e1==0 & df$n1==1,'A',df$tetlet)
      df$tetlet<-ifelse(df$e1==1 & df$n1==0,'A',df$tetlet)
      df$tetlet<-ifelse(df$e1==1 & df$n1==1,'A',df$tetlet)
      df$tetlet<-ifelse(df$e1==2 & df$n1==0,'F',df$tetlet)
      df$tetlet<-ifelse(df$e1==2 & df$n1==1,'F',df$tetlet)
      df$tetlet<-ifelse(df$e1==3 & df$n1==0,'F',df$tetlet)
      df$tetlet<-ifelse(df$e1==3 & df$n1==1,'F',df$tetlet)
      df$tetlet<-ifelse(df$e1==4 & df$n1==0,'K',df$tetlet)
      df$tetlet<-ifelse(df$e1==4 & df$n1==1,'K',df$tetlet)
      df$tetlet<-ifelse(df$e1==5 & df$n1==0,'K',df$tetlet)
      df$tetlet<-ifelse(df$e1==5 & df$n1==1,'K',df$tetlet)
      df$tetlet<-ifelse(df$e1==6 & df$n1==0,'Q',df$tetlet)
      df$tetlet<-ifelse(df$e1==6 & df$n1==1,'Q',df$tetlet)
      df$tetlet<-ifelse(df$e1==7 & df$n1==0,'Q',df$tetlet)
      df$tetlet<-ifelse(df$e1==7 & df$n1==1,'Q',df$tetlet)
      df$tetlet<-ifelse(df$e1==8 & df$n1==0,'V',df$tetlet)
      df$tetlet<-ifelse(df$e1==8 & df$n1==1,'V',df$tetlet)
      df$tetlet<-ifelse(df$e1==9 & df$n1==0,'V',df$tetlet)
      df$tetlet<-ifelse(df$e1==9 & df$n1==1,'V',df$tetlet)
      df$tetlet<-ifelse(df$e1==0 & df$n1==2,'B',df$tetlet)
      df$tetlet<-ifelse(df$e1==0 & df$n1==3,'B',df$tetlet)
      df$tetlet<-ifelse(df$e1==1 & df$n1==2,'B',df$tetlet)
      df$tetlet<-ifelse(df$e1==1 & df$n1==3,'B',df$tetlet)
      df$tetlet<-ifelse(df$e1==2 & df$n1==2,'G',df$tetlet)
      df$tetlet<-ifelse(df$e1==2 & df$n1==3,'G',df$tetlet)
      df$tetlet<-ifelse(df$e1==3 & df$n1==2,'G',df$tetlet)
      df$tetlet<-ifelse(df$e1==3 & df$n1==3,'G',df$tetlet)
      df$tetlet<-ifelse(df$e1==4 & df$n1==2,'L',df$tetlet)
      df$tetlet<-ifelse(df$e1==4 & df$n1==3,'L',df$tetlet)
      df$tetlet<-ifelse(df$e1==5 & df$n1==2,'L',df$tetlet)
      df$tetlet<-ifelse(df$e1==5 & df$n1==3,'L',df$tetlet)
      df$tetlet<-ifelse(df$e1==6 & df$n1==2,'R',df$tetlet)
      df$tetlet<-ifelse(df$e1==6 & df$n1==3,'R',df$tetlet)
      df$tetlet<-ifelse(df$e1==7 & df$n1==2,'R',df$tetlet)
      df$tetlet<-ifelse(df$e1==7 & df$n1==3,'R',df$tetlet)
      df$tetlet<-ifelse(df$e1==8 & df$n1==2,'W',df$tetlet)
      df$tetlet<-ifelse(df$e1==8 & df$n1==3,'W',df$tetlet)
      df$tetlet<-ifelse(df$e1==9 & df$n1==2,'W',df$tetlet)
      df$tetlet<-ifelse(df$e1==9 & df$n1==3,'W',df$tetlet)
      df$tetlet<-ifelse(df$e1==0 & df$n1==4,'C',df$tetlet)
      df$tetlet<-ifelse(df$e1==0 & df$n1==5,'C',df$tetlet)
      df$tetlet<-ifelse(df$e1==1 & df$n1==4,'C',df$tetlet)
      df$tetlet<-ifelse(df$e1==1 & df$n1==5,'C',df$tetlet)
      df$tetlet<-ifelse(df$e1==2 & df$n1==4,'H',df$tetlet)
      df$tetlet<-ifelse(df$e1==2 & df$n1==5,'H',df$tetlet)
      df$tetlet<-ifelse(df$e1==3 & df$n1==4,'H',df$tetlet)
      df$tetlet<-ifelse(df$e1==3 & df$n1==5,'H',df$tetlet)
      df$tetlet<-ifelse(df$e1==4 & df$n1==4,'M',df$tetlet)
      df$tetlet<-ifelse(df$e1==4 & df$n1==5,'M',df$tetlet)
      df$tetlet<-ifelse(df$e1==5 & df$n1==4,'M',df$tetlet)
      df$tetlet<-ifelse(df$e1==5 & df$n1==5,'M',df$tetlet)
      df$tetlet<-ifelse(df$e1==6 & df$n1==4,'S',df$tetlet)
      df$tetlet<-ifelse(df$e1==6 & df$n1==5,'S',df$tetlet)
      df$tetlet<-ifelse(df$e1==7 & df$n1==4,'S',df$tetlet)
      df$tetlet<-ifelse(df$e1==7 & df$n1==5,'S',df$tetlet)
      df$tetlet<-ifelse(df$e1==8 & df$n1==4,'X',df$tetlet)
      df$tetlet<-ifelse(df$e1==8 & df$n1==5,'X',df$tetlet)
      df$tetlet<-ifelse(df$e1==9 & df$n1==4,'X',df$tetlet)
      df$tetlet<-ifelse(df$e1==9 & df$n1==5,'X',df$tetlet)
      df$tetlet<-ifelse(df$e1==0 & df$n1==6,'D',df$tetlet)
      df$tetlet<-ifelse(df$e1==0 & df$n1==7,'D',df$tetlet)
      df$tetlet<-ifelse(df$e1==1 & df$n1==6,'D',df$tetlet)
      df$tetlet<-ifelse(df$e1==1 & df$n1==7,'D',df$tetlet)
      df$tetlet<-ifelse(df$e1==2 & df$n1==6,'I',df$tetlet)
      df$tetlet<-ifelse(df$e1==2 & df$n1==7,'I',df$tetlet)
      df$tetlet<-ifelse(df$e1==3 & df$n1==6,'I',df$tetlet)
      df$tetlet<-ifelse(df$e1==3 & df$n1==7,'I',df$tetlet)
      df$tetlet<-ifelse(df$e1==4 & df$n1==6,'N',df$tetlet)
      df$tetlet<-ifelse(df$e1==4 & df$n1==7,'N',df$tetlet)
      df$tetlet<-ifelse(df$e1==5 & df$n1==6,'N',df$tetlet)
      df$tetlet<-ifelse(df$e1==5 & df$n1==7,'N',df$tetlet)
      df$tetlet<-ifelse(df$e1==6 & df$n1==6,'T',df$tetlet)
      df$tetlet<-ifelse(df$e1==6 & df$n1==7,'T',df$tetlet)
      df$tetlet<-ifelse(df$e1==7 & df$n1==6,'T',df$tetlet)
      df$tetlet<-ifelse(df$e1==7 & df$n1==7,'T',df$tetlet)
      df$tetlet<-ifelse(df$e1==8 & df$n1==6,'Y',df$tetlet)
      df$tetlet<-ifelse(df$e1==8 & df$n1==7,'Y',df$tetlet)
      df$tetlet<-ifelse(df$e1==9 & df$n1==6,'Y',df$tetlet)
      df$tetlet<-ifelse(df$e1==9 & df$n1==7,'Y',df$tetlet)
      df$tetlet<-ifelse(df$e1==0 & df$n1==8,'E',df$tetlet)
      df$tetlet<-ifelse(df$e1==0 & df$n1==9,'E',df$tetlet)
      df$tetlet<-ifelse(df$e1==1 & df$n1==8,'E',df$tetlet)
      df$tetlet<-ifelse(df$e1==1 & df$n1==9,'E',df$tetlet)
      df$tetlet<-ifelse(df$e1==2 & df$n1==8,'J',df$tetlet)
      df$tetlet<-ifelse(df$e1==2 & df$n1==9,'J',df$tetlet)
      df$tetlet<-ifelse(df$e1==3 & df$n1==8,'J',df$tetlet)
      df$tetlet<-ifelse(df$e1==3 & df$n1==9,'J',df$tetlet)
      df$tetlet<-ifelse(df$e1==4 & df$n1==8,'P',df$tetlet)
      df$tetlet<-ifelse(df$e1==4 & df$n1==9,'P',df$tetlet)
      df$tetlet<-ifelse(df$e1==5 & df$n1==8,'P',df$tetlet)
      df$tetlet<-ifelse(df$e1==5 & df$n1==9,'P',df$tetlet)
      df$tetlet<-ifelse(df$e1==6 & df$n1==8,'U',df$tetlet)
      df$tetlet<-ifelse(df$e1==6 & df$n1==9,'U',df$tetlet)
      df$tetlet<-ifelse(df$e1==7 & df$n1==8,'U',df$tetlet)
      df$tetlet<-ifelse(df$e1==7 & df$n1==9,'U',df$tetlet)
      df$tetlet<-ifelse(df$e1==8 & df$n1==8,'Z',df$tetlet)
      df$tetlet<-ifelse(df$e1==8 & df$n1==9,'Z',df$tetlet)
      df$tetlet<-ifelse(df$e1==9 & df$n1==8,'Z',df$tetlet)
      df$tetlet<-ifelse(df$e1==9 & df$n1==9,'Z',df$tetlet)
      df$gref<-paste0(df$tenkm,df$tetlet)
    }

    #code up 1-km
    if(res==1) {
      df$gref<-paste0(df$hundref,df$e10,df$e1,df$n10,df$n1)
    }

    #tidy up
    df<-subset(df,select=c(dfnams,'gref'))
    n<-which(names(df)=='gref')
    names(df)[n]<-outname
    return(df)
  } #end check if res is an acceptable resolution
  #do not run if res is not an expected grid resolution
  if(!(res %in% c(1,2,10,20,50,100))) {
    cat('\nIncorrect resolution. Expecting one of 1, 2, 10, 20, 50, 100.')
  }
}
